//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUTHU
    {
<<<<<<< HEAD
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string MAPT { get; set; }

=======
        public int MAPT { get; set; }
>>>>>>> 6ca1b16fbfec224d65abaf0d7b0990ee83b71dc1
        public int MAPM { get; set; }
        public string MAND { get; set; }
<<<<<<< HEAD

        public int? TONGNO { get; set; }
        public int? TIENTHU { get; set; }

        public int? TIENCONLAI { get; set; }

        public DateTime TGPT { get; set; }

=======
        public Nullable<int> TIENTHU { get; set; }
        public Nullable<int> TIENCONLAI { get; set; }
        public System.DateTime TGPT { get; set; }
    
>>>>>>> 6ca1b16fbfec224d65abaf0d7b0990ee83b71dc1
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual PHIEUMUON PHIEUMUON { get; set; }
    }
}
